### ISSUE TITLE
Unmet dependencies under OpenSUSE Tumbleweed-Slowscroll

### ISSUE THREAD

**Issue by Sadi58** [ivan-hc/Spotify-appimage#1]
Launching the AppImage gave error messages for loading shared libraries, which required installing `libayatana-appindicator3-1` and `libatomic1`, but the next one required was `libcurl-gnutls4` which was (no longer) available in the repos, so I had to give up...

**Comment by ivan-hc** [comment]
This AppImage only bundles what the .deb package contain... I don't know if this can help, but to test any compatibility you may extract the appimage:
```
./*.AppImage --appimage-extract
```
edit the AppRun script like this
```
#!/bin/sh
HERE="$(dirname "$(readlink -f "${0}")")"
export PATH="${HERE}/opt/spotify/:${HERE}/opt/spotify/Apps/:${PATH:+:$PATH}"
export LD_LIBRARY_PATH=/lib/:/lib64/:/lib/x86_64-linux-gnu/:/usr/lib/:"${HERE}/opt/spotify/:${HERE}/opt/spotify/swiftshader/${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}"
export XDG_DATA_DIRS="${HERE}/opt/spotify/${XDG_DATA_DIRS:+:$XDG_DATA_DIRS}"
export GSETTINGS_SCHEMA_DIR="${HERE}/opt/spotify/swiftshader/${GSETTINGS_SCHEMA_DIR:+:$GSETTINGS_SCHEMA_DIR}"
EXEC="${HERE}/opt/spotify/spotify"
exec "${EXEC}"
```
and then run the AppRun script
```
./AppRun
```
with this change the AppImage should recognize the system libraries

EDIT: let me know if this works for you

**Comment by Sadi58** [comment]
@ivan-hc Oh! I've already attempted to use the DEB package which ended with unresolvable dependency problems. Although I've seen the statement that it "has been built from the official deb package" I just wanted to try and see if it contained those unmet dependencies as AppImages normally do.
I hope this experimental version can reach a mature state soon. I wish I could contribute. Thanks anyway...

**Comment by ivan-hc** [comment]
https://github.com/ivan-hc/Spotify-appimage/commit/d1a5f82643252ef1e6243be25158b091d2677bf7

@Sadi58 download it again, I've uncluded libcurl-gnutls libraries from Arch Linux as last reference in LD_LIBRARY_PATH, so in case they are not compatible on other systems, they will not be called, and if not available, they will be called.

Let me know if work.

**Comment by Sadi58** [comment]
Oh, it's working now!!! Thank you so much! ❤️
Now maybe I should try and learn some basic information about unpacking and repacking AppImage files so that I can change the system tray icon to match the Breeze icon theme as I did in the DEB installation under Debian: replacing the green "spotify-linux-16.png" "spotify-linux-22.png" "spotify-linux-24.png" "spotify-linux-32.png" in the directory "/usr/share/spotify/icons/" with monochrome ones.😉
